language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
script: bundle exec rspec spec
gemfile:
  - Gemfile
  - .gemfiles/2.2.2.gemfile
  - .gemfiles/2.2.3.gemfile
  - .gemfiles/2.3.2.gemfile
  - .gemfiles/2.3.3.gemfile
  - .gemfiles/2.3.4.gemfile
  - .gemfiles/2.3.5.gemfile
  - .gemfiles/2.3.6.gemfile
  - .gemfiles/2.3.7.gemfile
  - .gemfiles/2.3.8.gemfile
  - .gemfiles/2.3.9.gemfile
  - .gemfiles/2.3.10.gemfile
  - .gemfiles/2.3.11.gemfile
  - .gemfiles/2.3.12.gemfile
  - .gemfiles/2.3.14.gemfile
  - .gemfiles/3.0.0.gemfile
  - .gemfiles/3.0.1.gemfile
  - .gemfiles/3.0.2.gemfile
  - .gemfiles/3.0.3.gemfile
  - .gemfiles/3.0.4.gemfile
  - .gemfiles/3.0.5.gemfile
  - .gemfiles/3.0.6.gemfile
  - .gemfiles/3.0.7.gemfile
  - .gemfiles/3.0.8.gemfile
  - .gemfiles/3.0.9.gemfile
  - .gemfiles/3.0.10.gemfile
  - .gemfiles/3.0.11.gemfile
  - .gemfiles/3.0.12.gemfile
  - .gemfiles/3.1.0.gemfile
  - .gemfiles/3.1.1.gemfile
  - .gemfiles/3.1.2.gemfile
  - .gemfiles/3.1.3.gemfile
  - .gemfiles/3.1.4.gemfile
  - .gemfiles/3.2.0.gemfile
  - .gemfiles/3.2.1.gemfile
  - .gemfiles/3.2.2.gemfile
  - .gemfiles/3.2.3.gemfile
